sudo: required
services:
  - docker

before_install:
  - docker build -e CI=true -t hrmtsngh18/docker-react -f Dockerfile.dev .

script:
  - docker run hrmtsngh18/docker-react npm run test -- --coverage